- name: install and run nginx
  hosts: web
  tasks:
  - name: installing nginx package
    ansible.builtin.package:
      name: nginx
      state: absent
  - name: run nginx
    ansible.builtin.package:
      name: nginx
      state: stop
