- name: variables from palybook level
  hosts: localhosts
  vars:
    cource: "Devops"
    triner: "shivakumar"
    duration: "120days"
  tasks:
  - name: check variables
  ansible.builtin.debug:
    msg: "hai i am lerning {{cource}}, triner is {{triner}}, duration is {{duration}}" 
